[formatter.rustfmt]
command = "rustfmt"
options = ["--edition", "2024"]
includes = ["*.rs"]

[formatter.gofmt]
command = "gofmt"
options = ["-w"]
includes = ["*.go"]

[formatter.nixpkgs-fmt]
command = "nixpkgs-fmt"
includes = ["*.nix"]

[formatter.prettier]
command = "prettier"
options = ["--write"]
includes = ["*.json", "*.yml", "*.yaml", "*.md"]
excludes = ["Cargo.lock", "*.toml"]

[formatter.rubocop]
command = "rubocop"
options = ["--autocorrect", "--format", "quiet"]
includes = ["*.rb"]
